framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./src/.*"
postMerge:
  pattern: 
    - "./src/.*"
postRun:
     command:
        - yarn --version
version: 1.0
